## default connection pool
spring:
  mvc.date-format: yyyy-MM-dd'T'HH:mm:ss
  datasource.hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
server:
  servlet:
    session:
      timeout: 1h
## PostgreSQL
db:
  host: localhost
  port: 5432
  dbname: notes
  username: notes
  password: password

google:
  credentials: /data/secrets/laflemme-3b669604d7e6.json
fcm:
  credentials: /data/secrets/fcm.json

app:
  base:
    url: https://notes.jleo.tech

subs:
  store:
    path: /opt/data/korean-subs/store
  videoclipper:
    url: http://localhost:8080