## default connection pool
spring:
  mvc.date-format: yyyy-MM-dd'T'HH:mm:ss
  datasource.hikari:
    connectionTimeout: 20000
    maximumPoolSize: 5
server:
  servlet:
    session:
      timeout: 1h
## PostgreSQL
db:
  host: ${NOTES_DB_HOST:localhost}
  port: ${NOTES_DB_PORT:5432}
  dbname: ${NOTES_DB_NAME:notes}
  username: ${NOTES_DB_USERNAME:notes}
  password: ${NOTES_DB_PASSWORD:password}

app:
  base:
    url: https://notes.jleo.tech

subs:
  store:
    path: /opt/data/korean-subs/store
  videoclipper:
    url: ${CLIPPER_SERVICE_URL:http://localhost:8080}
  publisher:
    topicid: projects/laflemme/topics/subs
  reader:
    strategy: gcp
    subscription: projects/laflemme/subscriptions/subs-processed
  cloudstorage:
    projectId: laflemme
    bucketId: kovids


nlpsearch:
  url: ${NLP_SEARCH_URL:http://localhost:8000}
notes:
  publisher:
    strategy: gcp
    topicid: projects/laflemme/topics/notes

management:
  endpoints:
    web:
      exposure:
        include: prometheus