name: "Add SSH Connection"
description: "Coucou"
inputs:
  aliasname:
    required: true
    description: "Alias of the server used in ssh commands"
  user:
    required: true
    description: "User that will connect to the server"
  serverhost:
    required: true
    description: "IP or dns name of the server"
  envSSH_KEY:
    required: true
    description: "Private key to connect"
runs:
  using: "composite"
  steps:
    - name: Create Conf File
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/key.key
        chmod 600 ~/.ssh/key.key
        cat >>~/.ssh/config <<END
        Host ${{ inputs.aliasname }}
          HostName ${{ inputs.serverhost }}
          User ${{ inputs.user }}
          IdentityFile ~/.ssh/key.key
          StrictHostKeyChecking no
        END
      env:
        SSH_KEY: ${{ inputs.envSSH_KEY }}

